# Generated by Django 5.2.8 on 2026-08-22 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField(default=0)),
                ('start_at', models.DateTimeField()),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('carrier_name', models.CharField(blank=True, max_length=160)),
                ('main_office', models.CharField(blank=True, max_length=200)),
                ('truck_number', models.CharField(blank=True, max_length=80)),
                ('shipping_doc', models.CharField(blank=True, max_length=120)),
                ('plan', models.JSONField(default=dict)),
                ('provider', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
